# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab304d8632d2c80fdaad95c8e3946503116e37e15d13ac535814969750df1e6b3a5562076e2cf5a756da0a979d49bd008e29dbda582986cb879a0059bcc5b9bb

test:
  secret_key_base: 1bdcf34b11ffdd389eba537f259e8efe79054b6d9358ff7a59103f763168847878c02148bd4919bf098b2bf5a09384cf5b1db7f51c1a6bb8b5ca6d5566cec182

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
